'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LockTime.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 
        '''预定义的日期/时间格式
        '''下表标识预定义的日期和时间格式名称。 这些参数可以按名称用作 Format 函数的样式参数：
        '''格式名称                        描述
        '''General Date 或 G               显示日期和时间。 例如， 3/12/2008 11:07:31 AM 。 日期显示由应用程序的当前区域性值确定。
        '''Long Date 、 Medium Date 或 D   根据当前区域性的长日期格式显示日期。 例如， Wednesday, March 12, 2008 。
        '''Short Date 或 d                 使用当前区域性的短日期格式显示日期。 例如， 3/12/2008 。
        '''                                d 字符以用户定义的日期格式显示日期。
        '''Long Time 、 Medium Time 或 T   使用当前区域性的长时间格式显示时间;通常包括小时、分钟、秒。 例如， 11:07:31 AM 。
        '''Short Time 或 t                 使用当前区域性的短时间格式显示 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TimeFormat() As String
            Get
                Return ResourceManager.GetString("TimeFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 https://cjhdevact.github.io/otherprojects/LockTime/upinfo.json 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property updateurl() As String
            Get
                Return ResourceManager.GetString("updateurl", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
